apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: pongsak.sanguanwong@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-production
    # ACME DNS-01 provider configurations
    solvers:
    - selector: {}
      dns01:
        # Here we define a list of DNS-01 providers that can solve DNS challenges
        cloudflare:
          email: pongsak.sanguanwong@gmail.com
          # A secretKeyRef to a cloudflare api key
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
