---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-oozou-millnium
  namespace: kube-system
spec:
  secretName: wildcard-oozou-millnium
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "*.oozou.millenium-m.me"
